"""Compile an editor DAG to a bounded C++ recipe, regenerated by generate_assets.py."""
import json
import copy
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = json.loads((ROOT / 'tools/map_editor/schema.json').read_text())
OPS = {op['id']: (i, op) for i, op in enumerate(SCHEMA['operations'])}
LUT_MAX_POINTS = 255
PARAM_WORDS = 64
LUT_COLORS = ('#759bc7','#d6a466','#83ad79','#bd7f9f','#9a8ac7','#63aaa2','#c58a67','#a4a766')
LIBRARY_PATH = ROOT / 'maps/map-library.json'
MAP_ID = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
MAP_NAME = re.compile(r'^[A-Za-z0-9 .+\-/]+$')


def default_lut_color(value):
    return LUT_COLORS[((value * 37) ^ (value >> 2)) % len(LUT_COLORS)]


def integer(value, low, high, name):
    if type(value) is not int or not low <= value <= high:
        raise ValueError(f'{name} must be an integer between {low} and {high}')
    return value


def upgrade_node(node):
    if node.get('type') == 'material_fill':
        node['type'] = 'field_fill'
        if node.get('label') == 'Fill material':
            node['label'] = 'Constant field'
    if node.get('type') == 'material_paint':
        node['type'] = 'field_paint'
        if node.get('label') == 'Paint material':
            node['label'] = 'Paint field value'
    if node.get('type') == 'material_bands':
        params = node.get('p')
        if isinstance(params, list) and len(params) == 7:
            boundaries, values = params[:3], params[3:]
            initial, points = values[0], []
            for position, output in zip(boundaries, values[1:]):
                if position == 0:
                    initial = output
                elif points and points[-1][0] == position:
                    points[-1][1] = output
                else:
                    points.append([position, output])
            node['p'] = [len(points), initial, *(value for point in points for value in point)]
        node['type'] = 'field_lut'
        if node.get('label') == 'Field to materials':
            node['label'] = 'Stepped LUT'
    if node.get('type') == 'field_lut':
        params = node.get('p')
        if isinstance(params, list) and params and type(params[0]) is int and 0 <= params[0] <= LUT_MAX_POINTS:
            count = params[0]
            if len(params) >= 2 + count * 2:
                node['p'] = params = params[:2 + count * 2]
            outputs = [params[1] if len(params) > 1 else 0]
            outputs.extend(params[3 + index * 2] if len(params) > 3 + index * 2 else 0 for index in range(count))
            colors = node.get('colors') if isinstance(node.get('colors'), list) else []
            node['colors'] = [colors[index] if index < len(colors) and isinstance(colors[index], str) and
                              len(colors[index]) == 7 and colors[index][0] == '#' else default_lut_color(output)
                              for index, output in enumerate(outputs)]


def compiled_parameters(node):
    params = node['p']
    if node['type'] != 'field_lut':
        return params
    points = sorted((params[2 + index * 2], params[3 + index * 2]) for index in range(params[0]))
    lookup, output, point = [], params[1], 0
    for input_value in range(256):
        while point < len(points) and points[point][0] <= input_value:
            output = points[point][1]
            point += 1
        lookup.append(output)
    result = []
    for offset in range(0, 256, 4):
        word = sum(lookup[offset + byte] << (byte * 8) for byte in range(4))
        result.append(word - (1 << 32) if word >= (1 << 31) else word)
    return result


def compile_recipe(recipe, target=None):
    if recipe.get('version') not in (1, 2, 3):
        raise ValueError('Unsupported recipe version')
    integer(recipe.get('seed'), 0, 0xffffffff, 'Seed')
    nodes = recipe.get('nodes', [])
    if not 1 <= len(nodes) <= 32:
        raise ValueError('Recipe must contain 1 to 32 nodes')
    lookup = {}
    for node in nodes:
        upgrade_node(node)
        key = integer(node.get('id'), 1, 0x7fffffff, 'Node ID')
        if key in lookup or node.get('type') not in OPS:
            raise ValueError('Duplicate node ID or unknown operation')
        _, spec = OPS[node['type']]
        integer(node.get('stream', 0), 0, 0xffffffff, 'Random stream')
        params = node.get('p', [])
        if node['type'] == 'roads' and len(params) == 3:
            integer(params[0],8,256,'Minimum road width')
            integer(params[2],params[0],256,'Maximum road width')
            params=[params[0] if params[0]==params[2] else (params[0]+params[2]+8)//16*8,params[1]]
            node['p']=params
        if node['type'] == 'field_lut':
            if not params or type(params[0]) is not int or len(params) != 2 + params[0] * 2:
                raise ValueError(f'Invalid LUT data on node {key}')
            integer(params[0], 0, LUT_MAX_POINTS, 'Point count')
            integer(params[1], 0, 255, 'Initial output')
            for index in range(params[0]):
                integer(params[2 + index * 2], 1, 255, f'Point {index + 1} position')
                integer(params[3 + index * 2], 0, 255, f'Point {index + 1} output')
            positions = [params[2 + index * 2] for index in range(params[0])]
            if len(set(positions)) != len(positions):
                raise ValueError('Stepped LUT points need unique positions')
        else:
            if len(params) != len(spec['parameters']):
                raise ValueError(f'Wrong parameter count on node {key}')
            for value, param in zip(params, spec['parameters']):
                integer(value, param[2], param[3], param[0])
                if len(param) > 4 and param[4] == 'neighbours' and value not in (4, 8):
                    raise ValueError('Neighbourhood must be 4 or 8')
        lookup[key] = node
    if recipe['version'] == 2 and lookup.get(recipe.get('materialOutput'), {}).get('type') != 'materials':
        raise ValueError('Choose a Ground materials output')
    if recipe['version'] == 1 and recipe.get('materialOutput') is not None:
        raise ValueError('Material outputs require recipe version 2')
    for key,kind in [('materialOutput','materials'),('spawnOutput','spawns'),('decorationOutput','decoration')]:
        if recipe.get(key) is not None and lookup.get(recipe[key],{}).get('type')!=kind:
            raise ValueError('Invalid '+key)
    if recipe['version']<3 and any(recipe.get(k) is not None for k in ('spawnOutput','decorationOutput')):
        raise ValueError('Placement outputs require recipe version 3')
    order, visiting, done = [], set(), set()

    def visit(key):
        if type(key) is not int or key not in lookup:
            raise ValueError('Missing input or output node')
        if key in visiting:
            raise ValueError('Graph contains a cycle')
        if key in done:
            return
        visiting.add(key)
        node = lookup[key]
        spec = OPS[node['type']][1]
        inputs = node.get('inputs', {})
        if set(inputs) - set(spec['inputs']):
            raise ValueError('Unknown input port')
        for port, expected in spec['inputs'].items():
            source = inputs.get(port)
            if source is None and expected.endswith('?'):
                continue
            visit(source)
            if OPS[lookup[source]['type']][1]['kind'] != expected.rstrip('?'):
                raise ValueError(f'Wrong input type on node {key}: {port}')
        visiting.remove(key)
        done.add(key)
        order.append(key)

    # Validate disconnected draft branches too, but only export the output's ancestors.
    for key in lookup:
        visit(key)
    order.clear()
    done.clear()
    visit(recipe.get('output') if target is None else target)
    if target is None and lookup[recipe['output']]['type'] not in ('world', 'roads'):
        raise ValueError('ROM output must be a Playable world node')
    indices = {key: i for i, key in enumerate(order)}
    program = []
    for key in order:
        node = lookup[key]
        inputs = node.get('inputs', {})
        params = compiled_parameters(node)
        program.append([OPS[node['type']][0], *[indices.get(inputs.get(p), -1) for p in ('a', 'b', 'mask')],
                        node.get('stream', 0), *params, *([0] * (PARAM_WORDS-len(params)))])
    # Same conservative liveness schedule as the portable executor.
    last = list(range(len(program)))
    for i, node in enumerate(program):
        for source in node[1:4]:
            if source >= 0:
                last[source] = i
    peak = max(sum(end >= i for end in last[:i]) + 1 for i in range(len(program)))
    if peak > 6:
        raise ValueError(f'Recipe needs {peak} live buffers; the GBA limit is 6')
    return program


def validate_library(library, compile_maps=True):
    """Validate the shared editor/ROM catalog and return its enabled entries.

    Draft recipes intentionally receive only bounded structural checks. They
    may be incomplete while the user is building a graph. Enabled recipes must
    compile completely because they are emitted into the ROM title catalog.
    """
    if not isinstance(library, dict) or library.get('libraryVersion') != 1:
        raise ValueError('Unsupported map library format')
    entries = library.get('maps')
    if not isinstance(entries, list) or not 1 <= len(entries) <= 64:
        raise ValueError('Map library must contain between 1 and 64 maps')
    ids, enabled = set(), []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise ValueError(f'Map {index + 1} must be an object')
        map_id = entry.get('id')
        if not isinstance(map_id, str) or not MAP_ID.fullmatch(map_id) or len(map_id) > 48:
            raise ValueError(f'Map {index + 1} has an invalid ID')
        if map_id in ids:
            raise ValueError(f'Duplicate map ID: {map_id}')
        ids.add(map_id)
        if type(entry.get('includeInGame')) is not bool:
            raise ValueError(f'Map {map_id} needs an includeInGame flag')
        recipe = entry.get('recipe')
        if not isinstance(recipe, dict):
            raise ValueError(f'Map {map_id} needs a recipe')
        name = recipe.get('name')
        if not isinstance(name, str) or not 1 <= len(name) <= 24 or not MAP_NAME.fullmatch(name):
            raise ValueError(f'Map {map_id} name must use 1-24 title-safe characters')
        if recipe.get('version') not in (1, 2, 3):
            raise ValueError(f'Map {map_id} has an unsupported recipe version')
        integer(recipe.get('seed'), 0, 0xffffffff, f'Map {map_id} seed')
        nodes = recipe.get('nodes')
        if not isinstance(nodes, list) or len(nodes) > 32:
            raise ValueError(f'Map {map_id} must contain at most 32 nodes')
        if entry['includeInGame']:
            if not nodes:
                raise ValueError(f'Map {map_id} is enabled but its graph is empty')
            if compile_maps:
                candidate = copy.deepcopy(recipe)
                compile_recipe(candidate)
                for key in ('materialOutput', 'spawnOutput', 'decorationOutput'):
                    if candidate.get(key) is not None:
                        compile_recipe(candidate, candidate[key])
            enabled.append(entry)
    if not enabled:
        raise ValueError('Enable at least one valid map for the game')
    return enabled


def library_revision(data):
    return hashlib.sha256(data).hexdigest()


def load_library(path=LIBRARY_PATH, compile_maps=True):
    data = path.read_bytes()
    library = json.loads(data)
    enabled = validate_library(library, compile_maps)
    return library, enabled, library_revision(data)


def _program(text, symbol, program, fallback_op):
    rows = program or [[OPS[fallback_op][0], -1, -1, -1, 0, *([0] * PARAM_WORDS)]]
    text += f'inline constexpr mapgen::node {symbol}[]={{\n'
    for node in rows:
        text += '    {mapgen::op('+str(node[0])+'),'+','.join(map(str, node[1:5]))+'u,{'+','.join(map(str, node[5:]))+'}},\n'
    return text + '};\n'


def generate():
    library, entries, revision = load_library()
    text = '// Generated from maps/map-library.json ('+revision[:12]+'). Do not edit.\n#pragma once\n#include "map_recipe.h"\n'
    text += 'namespace map_catalog {\nstruct entry {\n    const char* id; const char* name; uint32_t seed;\n'
    text += '    const mapgen::node* nodes; int count;\n    const mapgen::node* material_nodes; int material_count;\n'
    text += '    const mapgen::node* spawn_nodes; int spawn_count;\n    const mapgen::node* decoration_nodes; int decoration_count;\n};\n'
    compiled = []
    for index, entry in enumerate(entries):
        recipe = copy.deepcopy(entry['recipe'])
        branches = {
            'nodes': compile_recipe(recipe),
            'material_nodes': compile_recipe(recipe, recipe['materialOutput']) if recipe.get('materialOutput') is not None else [],
            'spawn_nodes': compile_recipe(recipe, recipe['spawnOutput']) if recipe.get('spawnOutput') is not None else [],
            'decoration_nodes': compile_recipe(recipe, recipe['decorationOutput']) if recipe.get('decorationOutput') is not None else [],
        }
        for name, program in branches.items():
            fallback = 'materials' if name == 'material_nodes' else 'spawns' if name == 'spawn_nodes' else 'decoration' if name == 'decoration_nodes' else 'world'
            text = _program(text, f'map_{index}_{name}', program, fallback)
        compiled.append((entry, recipe, branches))
    text += 'inline constexpr entry maps[]={\n'
    for index, (entry, recipe, branches) in enumerate(compiled):
        fields = []
        for name in ('nodes', 'material_nodes', 'spawn_nodes', 'decoration_nodes'):
            fields.extend((f'map_{index}_{name}', str(len(branches[name]))))
        text += '    {'+json.dumps(entry['id'])+','+json.dumps(recipe['name'].upper())+','+str(recipe['seed'])+'u,'+','.join(fields)+'},\n'
    text += '};\ninline constexpr int count=sizeof(maps)/sizeof(maps[0]);\n}\n'
    output = ROOT / 'include/generated/wasteland_recipe.h'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    snapshot=ROOT/'artifacts/wasteland/active-map-library.json'
    snapshot.parent.mkdir(parents=True,exist_ok=True)
    snapshot.write_text(json.dumps(library,indent=2)+'\n')
    print(f'Map library: {len(entries)} game maps / {len(library["maps"])-len(entries)} drafts')


if __name__ == '__main__':
    generate()
