"""Compile an editor DAG to a bounded C++ recipe, regenerated by generate_assets.py."""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = json.loads((ROOT / 'tools/map_editor/schema.json').read_text())
OPS = {op['id']: (i, op) for i, op in enumerate(SCHEMA['operations'])}


def integer(value, low, high, name):
    if type(value) is not int or not low <= value <= high:
        raise ValueError(f'{name} must be an integer between {low} and {high}')
    return value


def compile_recipe(recipe, target=None):
    if recipe.get('version') not in (1, 2, 3):
        raise ValueError('Unsupported recipe version')
    integer(recipe.get('seed'), 0, 0xffffffff, 'Seed')
    nodes = recipe.get('nodes', [])
    if not 1 <= len(nodes) <= 32:
        raise ValueError('Recipe must contain 1 to 32 nodes')
    lookup = {}
    for node in nodes:
        key = integer(node.get('id'), 1, 0x7fffffff, 'Node ID')
        if key in lookup or node.get('type') not in OPS:
            raise ValueError('Duplicate node ID or unknown operation')
        _, spec = OPS[node['type']]
        integer(node.get('stream', 0), 0, 0xffffffff, 'Random stream')
        params = node.get('p', [])
        if node['type'] == 'roads' and len(params) == 3:
            integer(params[0],8,256,'Minimum road width')
            integer(params[2],params[0],256,'Maximum road width')
            params=[params[0] if params[0]==params[2] else (params[0]+params[2]+8)//16*8,params[1]]
            node['p']=params
        if len(params) != len(spec['parameters']):
            raise ValueError(f'Wrong parameter count on node {key}')
        for value, param in zip(params, spec['parameters']):
            integer(value, param[2], param[3], param[0])
            if len(param) > 4 and param[4] == 'neighbours' and value not in (4, 8):
                raise ValueError('Neighbourhood must be 4 or 8')
        if node['type'] == 'material_bands' and not params[0] <= params[1] <= params[2]:
            raise ValueError('Material boundaries must be in ascending order')
        lookup[key] = node
    if recipe['version'] == 2 and lookup.get(recipe.get('materialOutput'), {}).get('type') != 'materials':
        raise ValueError('Choose a Ground materials output')
    if recipe['version'] == 1 and recipe.get('materialOutput') is not None:
        raise ValueError('Material outputs require recipe version 2')
    for key,kind in [('materialOutput','materials'),('spawnOutput','spawns'),('decorationOutput','decoration')]:
        if recipe.get(key) is not None and lookup.get(recipe[key],{}).get('type')!=kind:
            raise ValueError('Invalid '+key)
    if recipe['version']<3 and any(recipe.get(k) is not None for k in ('spawnOutput','decorationOutput')):
        raise ValueError('Placement outputs require recipe version 3')
    order, visiting, done = [], set(), set()

    def visit(key):
        if type(key) is not int or key not in lookup:
            raise ValueError('Missing input or output node')
        if key in visiting:
            raise ValueError('Graph contains a cycle')
        if key in done:
            return
        visiting.add(key)
        node = lookup[key]
        spec = OPS[node['type']][1]
        inputs = node.get('inputs', {})
        if set(inputs) - set(spec['inputs']):
            raise ValueError('Unknown input port')
        for port, expected in spec['inputs'].items():
            source = inputs.get(port)
            if source is None and expected.endswith('?'):
                continue
            visit(source)
            if OPS[lookup[source]['type']][1]['kind'] != expected.rstrip('?'):
                raise ValueError(f'Wrong input type on node {key}: {port}')
        visiting.remove(key)
        done.add(key)
        order.append(key)

    # Validate disconnected draft branches too, but only export the output's ancestors.
    for key in lookup:
        visit(key)
    order.clear()
    done.clear()
    visit(recipe.get('output') if target is None else target)
    if target is None and lookup[recipe['output']]['type'] not in ('world', 'roads'):
        raise ValueError('ROM output must be a Playable world node')
    indices = {key: i for i, key in enumerate(order)}
    program = []
    for key in order:
        node = lookup[key]
        inputs = node.get('inputs', {})
        program.append([OPS[node['type']][0], *[indices.get(inputs.get(p), -1) for p in ('a', 'b', 'mask')],
                        node.get('stream', 0), *node['p'], *([0] * (8-len(node['p'])))])
    # Same conservative liveness schedule as the portable executor.
    last = list(range(len(program)))
    for i, node in enumerate(program):
        for source in node[1:4]:
            if source >= 0:
                last[source] = i
    peak = max(sum(end >= i for end in last[:i]) + 1 for i in range(len(program)))
    if peak > 6:
        raise ValueError(f'Recipe needs {peak} live buffers; the GBA limit is 6')
    return program


def generate():
    source = Path(os.environ.get('DUSTLINE_RECIPE', 'maps/wasteland.json'))
    if source.is_absolute() or '..' in source.parts:
        raise ValueError('Recipe path must be relative to the project directory')
    recipe = json.loads((ROOT / source).read_text())
    program = compile_recipe(recipe)
    text = '// Generated from '+source.as_posix()+'. Do not edit.\n#pragma once\n#include "map_recipe.h"\n'
    text += 'namespace active_recipe {\ninline constexpr uint32_t seed='+str(recipe['seed'])+'u;\ninline constexpr mapgen::node nodes[]={\n'
    for node in program:
        text += '    {mapgen::op('+str(node[0])+'),'+','.join(map(str, node[1:5]))+'u,{'+','.join(map(str, node[5:]))+'}},\n'
    text += '};\ninline constexpr int count=sizeof(nodes)/sizeof(nodes[0]);\n'
    material_program = compile_recipe(recipe, recipe['materialOutput']) if recipe.get('materialOutput') is not None else []
    text += 'inline constexpr mapgen::node material_nodes[]={\n'
    for node in material_program or [[12, -1, -1, -1, 0, 0]]:
        text += '    {mapgen::op('+str(node[0])+'),'+','.join(map(str,node[1:5]))+'u,{'+','.join(map(str,node[5:]))+'}},\n'
    text += '};\ninline constexpr int material_count='+str(len(material_program))+';\n'
    for name,key in [('spawn','spawnOutput'),('decoration','decorationOutput')]:
        branch=compile_recipe(recipe,recipe[key]) if recipe.get(key) is not None else []
        text+='inline constexpr mapgen::node '+name+'_nodes[]={\n'
        for node in branch or [[20,-1,-1,-1,0,0]]:
            text+='    {mapgen::op('+str(node[0])+'),'+','.join(map(str,node[1:5]))+'u,{'+','.join(map(str,node[5:]))+'}},\n'
        text+='};\ninline constexpr int '+name+'_count='+str(len(branch))+';\n'
    text+='}\n'
    output = ROOT / 'include/generated/wasteland_recipe.h'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    snapshot=ROOT/'artifacts/wasteland/active-recipe.json'
    snapshot.parent.mkdir(parents=True,exist_ok=True)
    snapshot.write_text(json.dumps(recipe,indent=2)+'\n')
    print(f'Recipe: {recipe.get("name", "Untitled")} / {len(program)} operations')


if __name__ == '__main__':
    generate()
