"""Reference-derived tiles + UI. Layouts are generated by the shared C++ CA code."""
import hashlib
import json
import struct
import subprocess
from pathlib import Path
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'maps/overworld'
OUT=ROOT/'artifacts/wasteland'


def generate(ui_palette,save,label):
    from generate_materials import generate as generate_material_catalog
    catalog=generate_material_catalog()
    OUT.mkdir(parents=True,exist_ok=True)
    source=Image.open(ASSETS/'wasteland-kit-muted.png').convert('RGBA')
    composite=Image.new('RGB',source.size,(132,112,88)); composite.paste(source,mask=source.getchannel('A'))
    adaptive=composite.quantize(colors=208,method=Image.Quantize.MEDIANCUT)
    # Round colours to hardware RGB5 before mapping, and retain the common UI slots.
    material_palette=[(c//8)*8 for c in adaptive.getpalette()[:624]]
    # RGB5 rounding leaves duplicate palette entries. Compact them losslessly,
    # retaining UI indices 0..15 and reserving separate 4bpp UI/scenery banks.
    colors=[tuple(ui_palette[i:i+3]) for i in range(0,48,3)]
    remap=[]
    for i in range(0,624,3):
        color=tuple(material_palette[i:i+3])
        if color not in colors[1:]: colors.append(color)
        remap.append(colors.index(color,1))  # Opaque terrain must never become index zero.
    palette_colors=(len(colors)+15)//16*16
    assert palette_colors<=224, 'Reserve separate UI and scenery palette banks'
    full_palette=[c for color in colors for c in color]+[0]*(768-len(colors)*3)
    pal=Image.new('P',(1,1)); pal.putpalette(material_palette+material_palette[:144])
    def indexed(im):
        result=im.convert('RGB').quantize(palette=pal,dither=Image.Dither.NONE)
        result=result.point([remap[i%208] for i in range(256)]); result.putpalette(full_palette)
        return result
    def cell(x,y):
        return source.crop((round(x*source.width/4),round(y*source.height/2),
                            round((x+1)*source.width/4),round((y+1)*source.height/2)))
    textures=[indexed(cell(x,y).resize((32,32),Image.Resampling.NEAREST))
              for x,y in [(0,0),(1,0),(2,0),(3,0),(0,1),(1,1)]]
    icons=[]
    for column in (2,3):
        art=cell(column,1)
        alpha=art.getchannel('A').point(lambda value:255 if value>=192 else 0)
        # Cell rims are not part of the icon. Preserve the supplied alpha inside.
        ImageDraw.Draw(alpha).rectangle((0,0,alpha.width-1,6),fill=0)
        ImageDraw.Draw(alpha).rectangle((0,alpha.height-7,alpha.width-1,alpha.height-1),fill=0)
        art.putalpha(alpha); bounds=alpha.getbbox()
        if not bounds: raise ValueError('Generated town icon is empty')
        art=art.crop(bounds); art.thumbnail((56,56),Image.Resampling.NEAREST)
        base=Image.new('P',(64,64)); base.putpalette(full_palette)
        for y in range(64):
            for x in range(64): base.putpixel((x,y),textures[0].getpixel((x%32,(y+16)%32)))
        base.paste(indexed(art),((64-art.width)//2,(64-art.height)//2),art.getchannel('A'))
        icons.append(base)
    from generate_assets import decoration_tiles
    decoration=decoration_tiles(full_palette)
    unique=[]; lookup={}; refs=[]
    for art in textures+icons:
        for y in range(0,art.height,8):
            for x in range(0,art.width,8):
                tile=art.crop((x,y,x+8,y+8)).tobytes()
                if tile not in lookup: lookup[tile]=len(unique); unique.append(tile)
                refs.append(lookup[tile])
    slots=(len(unique)+31)//32*32
    assert slots<=256, 'Keep the entire wasteland art vocabulary within 16 KiB terrain VRAM'
    header='#pragma once\n#include "bn_tile.h"\n#include "bn_color.h"\nnamespace wasteland_art {\n'
    header+=f'inline constexpr int tile_slots={slots},unique_tiles={len(unique)},palette_colors={palette_colors};\n'
    header+='inline constexpr unsigned short refs[] = {'+','.join(map(str,refs))+'};\n'
    header+='inline constexpr bn::color palette[] = {'+','.join(
        f'bn::color({full_palette[i]//8},{full_palette[i+1]//8},{full_palette[i+2]//8})' for i in range(0,768,3))+'};\n'
    header+=f'inline constexpr bn::tile tiles[{len(unique)*2}] = {{\n'
    header+='\n'.join('{{'+','.join(hex(v) for v in struct.unpack('<8I',tile[i:i+32]))+'}},'
                       for tile in unique for i in (0,32))+'\n};\n}\n'
    (ROOT/'include/generated/wasteland_art.h').write_text(header)
    atlas=Image.new('P',(128,128)); atlas.putpalette(full_palette)
    for i,art in enumerate(textures): atlas.paste(art,(i%4*32,i//4*32))
    atlas.paste(icons[0],(0,64)); atlas.paste(icons[1],(64,64)); atlas.save(OUT/'tiles.png')
    (OUT/'art-refs.bin').write_bytes(struct.pack('<'+str(len(refs))+'H',*refs)+b''.join(unique))
    (OUT/'palette.bin').write_bytes(bytes(full_palette))
    editor=ROOT/'tools/map_editor/generated'
    editor.mkdir(parents=True,exist_ok=True)
    (editor/'art.json').write_text(json.dumps(dict(
        refs=refs,tiles=list(b''.join(unique)),palette=full_palette,catalog=catalog,decoration=decoration),separators=(',',':')))
    hud=Image.open(ROOT/'graphics/hud.bmp').copy(); hud.putpalette(full_palette)
    save('hud_waste',hud,'regular_bg',bpp_mode='bpp_4')
    pause=Image.open(ROOT/'graphics/pause.bmp').copy(); pause.putpalette(full_palette)
    save('pause_waste',pause,'regular_bg',bpp_mode='bpp_4')
    blank=Image.new('P',(256,256),1); blank.putpalette(full_palette)
    save('town_blank',blank,'regular_bg',bpp_mode='bpp_4')
    dialog=Image.new('P',(256,256),0); dialog.putpalette(full_palette)
    ImageDraw.Draw(dialog).rectangle((16,160,239,205),fill=1,outline=11,width=1)
    save('town_dialog',dialog,'regular_bg',bpp_mode='bpp_4')
    subprocess.run(['g++','-std=c++17','-O2','-Wall','-Wextra','-Iinclude','tools/test_cave_layout.cpp',
                    '-o','build/test_cave_layout'],cwd=ROOT,check=True)
    subprocess.run(['build/test_cave_layout',str(0xC0FFEE),'artifacts/wasteland/fixed.bin'],cwd=ROOT,check=True)
    raw=(OUT/'fixed.bin').read_bytes(); info=struct.unpack_from('<8I',raw)
    columns=info[0]; extent=columns*128
    cells=raw[80:]; assert len(cells)==columns*columns
    overview=Image.frombytes('L',(columns,columns),bytes(35 if v else 190 for v in cells)).convert('RGB')
    overview=overview.resize((1024,1024),Image.Resampling.NEAREST); d=ImageDraw.Draw(overview)
    for i in range(6):
        x,y=struct.unpack_from('<2I',raw,32+i*8); x=x*1024//extent;y=y*1024//extent
        d.rectangle((x-3,y-3,x+3,y+3),fill=(90,210,210))
    x,y=info[6]*1024//extent,info[7]*1024//extent; d.rectangle((x-3,y-3,x+3,y+3),fill=(250,90,60))
    overview.save(OUT/'fixed-layout.png')
    report=dict(width=extent,height=extent,logical_grid=[columns,columns],cell_size=128,fixed_seed=info[2],
                fixed_signature=info[3],fixed_floor_cells=info[4],towns=6,
                unique_tiles=len(unique),tile_slots=slots,terrain_vram_bytes=slots*64,palette_colors=palette_colors,
                art_source_sha256=hashlib.sha256((ASSETS/'wasteland-kit-muted.png').read_bytes()).hexdigest(),
                reference_sha256=hashlib.sha256((ROOT/'maps/open_world/wasteland.png').read_bytes()).hexdigest())
    (OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n')
    print('Wasteland:',report,flush=True)
